#DB 설정
spring:
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:tcp://localhost/~/waveit
    username: sa
    password: 1230

  #JPA 설정
  jpa:
    database-platform:
    hibernate:
      #ddl-auto는 배포 시 변경 필요
      ddl-auto: create

    #배포 할 떄는 open-in-view false 설정
    open-in-view: false
    properties:
      hibernate:
        show_sql: true
        format_sql: true

# logging 설정
logging:
  level:
    org:
      hibernate:
        type:
          descriptor:
            sql: debug

# 오류 처리
server:
  error:
    include-exception: true
    include-stacktrace: always

#port 설정
port: 8080